/** Login Mutations types**/
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

/** Authentication Mutation types**/
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_FAILED = "REGISTER_FAILED";

/** User profile Mutation types **/
export const PROFILE = "PPROFILE";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";
export const PROFILE_ERROR = "PROFILE_ERROR";

/** User profile update mutation types **/
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

/** Repayment Schedule Mutation types **/
export const NEWS_DATA = "NEWS_DATA";
export const NEWS_DATA_SUCCESS = "NEWS_DATA_SUCCESS";
export const NEWS_DATA_ERROR = " NEWS_DATA_ERROR ";
export const NEWS_DATA_FAILED = "NEWS_DATA_FAILED";

export const NEWS_DATAS = "NEWS_DATAS";
export const NEWS_DATAS_SUCCESS = "NEWS_DATAS_SUCCESS ";
export const NEWS_DATAS_ERROR = " NEWS_DATAS_ERROR";
export const NEWS_DATAS_FAILED = "NEWS_DATAS_FAILED";

export const SAVE_NEWS_DATA = "SAVE_NEWS_DATA";
export const SAVE_NEWS_DATA_SUCCESS = "SAVE_NEWS_DATA_SUCCESS";
export const SAVE_NEWS_DATA_ERROR = "SAVE_NEWS_DATA_ERROR ";
export const SAVE_NEWS_DATA_FAILED = "SAVE_NEWS_DATA_FAILED";

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS";
export const GET_ALL_QUESTIONS_ERROR = "GET_ALL_QUESTIONS_ERROR";
export const GET_ALL_QUESTIONS_FAILED = "GET_ALL_QUESTIONS_FAILED";

export const GET_ALL_QUESTIONS_SOURCE = "GET_ALL_QUESTIONS_SOURCE";
export const GET_ALL_QUESTIONS_SOURCE_SUCCESS =
  "GET_ALL_QUESTIONS_SOURCE_SUCCESS";
export const GET_ALL_QUESTIONS_SOURCE_ERROR = "GET_ALL_QUESTIONS_SOURCE_ERROR";
export const GET_ALL_QUESTIONS_SOURCE_FAILED =
  "GET_ALL_QUESTIONS_SOURCE_FAILED";

export const GET_SECTORS = "GET_SECTORS";
export const GET_SECTORS_SUCCESS = "GET_SECTORS_SUCCESS";
export const GET_SECTORS_ERROR = "GET_SECTORS_ERROR";
export const GET_SECTORS_FAILED = "GET_SECTORS_FAILER";

export const GET_CURRENT_RELEASES = "GET_CURRENT_RELEASES";
export const GET_CURRENT_RELEASES_SUCCESS = "GET_CURRENT_RELEASES_SUCCESS";
export const GET_CURRENT_RELEASES_FAILLED = "GET_CURRENT_RELEASES_FAILLED";
export const GET_CURRENT_RELEASES_ERROR = "GET_CURRENT_RELEASES_ERROR";

export const GET_DISAGGREGATIONS = "GET_DISAGGREGATIONS";
export const GET_DISAGGREGATIONS_SUCCESS = "GET_DISAGGREGATIONS_SUCCESS";
export const GET_DISAGGREGATIONS_FAILLED = "GET_DISAGGREGATIONS_FAILLED";
export const GET_DISAGGREGATIONS_ERROR = "GET_DISAGGREGATIONS_ERROR";

export const GET_DISAGGREGATIONS_VALUES = "GET_DISAGGREGATIONS_VALUES";
export const GET_DISAGGREGATIONS_VALUES_SUCCESS =
  "GET_DISAGGREGATIONS_VALUES_SUCCESS";
export const GET_DISAGGREGATIONS_VALUES_FAILLED =
  "GET_DISAGGREGATIONS_VALUES_FAILLED";
export const GET_DISAGGREGATIONS_VALUES_ERROR =
  "GET_DISAGGREGATIONS_VALUES_ERROR";

export const GET_LOGINS_VALUES = "GET_LOGINS_VALUES";
export const GET_LOGINS_VALUES_SUCCESS = "GET_LOGINS_VALUES_SUCCESS";
export const GET_LOGINS_VALUES_FAILED = "GET_LOGINS_VALUES_FAILLED";
export const GET_LOGINS_VALUES_ERROR = "GET_LOGINS_VALUES_ERROR";

export const GET_MAINLAND_VALUES = "GET_MAINLAND_VALUES";
export const GET_MAINLAND_VALUES_SUCCESS = "GET_MAINLAND_VALUES_SUCCESS";
export const GET_MAINLAND_VALUES_FAILLED = "GET_MAINLAND_VALUES_FAILLED";
export const GET_MAINLAND_VALUES_ERROR = "GET_MAINLAND_VALUES_ERROR";

export const GET_PERIODTYPES_VALUES = "GET_PERIODTYPES_VALUES";
export const GET_PERIODTYPES_VALUES_SUCCESS = "GET_PERIODTYPES_VALUES_SUCCESS";
export const GET_PERIODTYPES_VALUES_FAILLED = "GET_PERIODTYPES_VALUES_FAILLED";
export const GET_PERIODTYPES_VALUES_ERROR = "GET_PERIODTYPES_VALUES_ERROR";

export const GET_REGULAR_INDICATOR_VALUES = "GET_REGULAR_INDICATOR_VALUES";
export const GET_REGULAR_INDICATOR_VALUES_SUCCESS =
  "GET_REGULAR_INDICATOR_VALUES_SUCCESS";
export const GET_REGULAR_INDICATOR_VALUES_FAILED =
  "GET_REGULAR_INDICATOR_VALUES_FAILED";
export const GET_REGULAR_INDICATOR_VALUES_ERROR =
  "GET_REGULAR_INDICATOR_VALUES_ERROR";

export const GET_PRIVILEGE_VALUES = "GET_PRIVILEGE_VALUES";
export const GET_PRIVILEGE_VALUES_SUCCESS = "GET_PRIVILEGE_VALUES_SUCCESS";
export const GET_PRIVILEGE_VALUES_FAILLED = "GET_PRIVILEGE_VALUES_FAILLED";
export const GET_PRIVILEGE_VALUES_ERROR = "GET_PRIVILEGE_VALUES_ERROR";

export const GET_PUBLICATIONS_VALUES = "GET_PUBLICATIONS_VALUES";
export const GET_PUBLICATIONS_VALUES_SUCCESS =
  "GET_PUBLICATIONS_VALUES_SUCCESS";
export const GET_PUBLICATIONS_VALUES_FAILLED =
  "GET_PUBLICATIONS_VALUES_FAILLED";
export const GET_PUBLICATIONS_VALUES_ERROR = "GET_PUBLICATIONS_VALUES_ERROR";

export const GET_RURALS_VALUES = "GET_RURALS_VALUES";
export const GET_RURALS_VALUES_SUCCESS = "GET_RURALS_VALUES_SUCCESS";
export const GET_RURALS_VALUES_FAILLED = "GET_RURALS_VALUES_FAILLED";
export const GET_RURALS_VALUES_ERROR = "GET_RURALS_VALUES_ERROR";

export const GET_TOTALFEMALE_VALUES = "GET_TOTALFEMALE_VALUES";
export const GET_TOTALFEMALE_VALUES_SUCCESS = "GET_TOTALFEMALE_VALUES_SUCCESS";
export const GET_TOTALFEMALE_VALUES_FAILLED = "GET_TOTALFEMALE_VALUES_FAILLED";
export const GET_TOTALFEMALE_VALUES_ERROR = "GET_TOTALFEMALE_VALUES_ERROR";

export const GET_INDICATOR_CATEGORIES = "GET_INDICATOR_CATEGORIES";
export const GET_INDICATOR_CATEGORIES_SUCCESS =
  "GET_INDICATOR_CATEGORIES_SUCCESS";
export const GET_INDICATOR_CATEGORIES_FAILED =
  "GET_INDICATOR_CATEGORIES_FAILED";
export const GET_INDICATOR_CATEGORIES_ERROR = "GET_INDICATOR_CATEGORIES_ERROR";

export const GET_INDICATOR_VALUES = "GET_INDICATOR_VALUES";
export const GET_INDICATOR_VALUES_SUCCESS = "GET_INDICATOR_VALUES_SUCCESS";
export const GET_INDICATOR_VALUES_FAILED = "GET_INDICATOR_VALUES_FAILED";
export const GET_INDICATOR_VALUES_ERROR = "GET_INDICATOR_VALUES_ERROR";

export const GET_SOURCE_GROUP = "GET_SOURCE_GROUP";
export const GET_SOURCE_GROUP_SUCCESS = "GET_SOURCE_GROUP_SUCCESS";
export const GET_SOURCE_GROUP_FAILED = "GET_SOURCE_GROUP_FAILED";
export const GET_SOURCE_GROUP_ERROR = "GET_SOURCE_GROUP_ERROR";

export const CREATE_SECTOR = "CREATE_SECTOR";
export const CREATE_SECTOR_SUCCESS = "CREATE_SECTOR_SUCCESS";
export const CREATE_SECTOR_FAILED = "CREATE_SECTOR_FAILLED";
export const CREATE_SECTOR_ERROR = "CREATE_SECTOR_ERROR";

export const POST_CURRENT_RELEASES = "POST_CURRENT_RELEASES";
export const POST_CURRENT_RELEASES_SUCCESS = "POST_CURRENT_RELEASES_SUCCESS";
export const POST_CURRENT_RELEASES_FAILED = "POST_CURRENT_RELEASES_FAILLED";
export const POST_CURRENT_RELEASES_ERROR = "POST_CURRENT_RELEASES_ERROR";

export const POST_DISAGGREGATION = "POST_DISAGGREGATION";
export const POST_DISAGGREGATION_SUCCESS = "POST_DISAGGREGATION_SUCCESS";
export const POST_DISAGGREGATION_FAILED = "POST_DISAGGREGATION_FAILLED";
export const POST_DISAGGREGATION_ERROR = "POST_DISAGGREGATION_ERROR";

export const POST_DISAGGREGATION_VALUE = "POST_DISAGGREGATION_VALUE";
export const POST_DISAGGREGATION_VALUE_SUCCESS =
  "POST_DISAGGREGATION_VALUE_SUCCESS";
export const POST_DISAGGREGATION_VALUE_FAILED =
  "POST_DISAGGREGATION_VALUE_FAILLED";
export const POST_DISAGGREGATION_VALUE_ERROR =
  "POST_DISAGGREGATION_VALUE_ERROR";

export const POST_INDICATOR_VALUE = "POST_INDICATOR_VALUE";
export const POST_INDICATOR_VALUE_SUCCESS = "POST_INDICATOR_VALUE_SUCCESS";
export const POST_INDICATOR_VALUE_FAILED = "POST_INDICATOR_VALUE_FAILLED";
export const POST_INDICATOR_VALUE_ERROR = "POST_INDICATOR_VALUE_ERROR";

export const POST_INDICATOR_SOURCE_VALUE = "POST_INDICATOR_SOURCE_VALUE";
export const POST_INDICATOR_SOURCE_VALUE_SUCCESS =
  "POST_INDICATOR_SOURCE_VALUE_SUCCESS";
export const POST_INDICATOR_SOURCE_VALUE_FAILED =
  "POST_INDICATOR_SOURCE_VALUE_FAILED";
export const POST_INDICATOR_SOURCE_VALUE_ERROR =
  "POST_INDICATOR_SOURCE_VALUE_ERROR";

export const POST_INDICATOR_PERIOD_TYPE_VALUE =
  "POST_INDICATOR_PERIOD_TYPE_VALUE";
export const POST_INDICATOR_PERIOD_TYPE_VALUE_SUCCESS =
  "POST_INDICATOR_PERIOD_TYPE_VALUE_SUCCESS";
export const POST_INDICATOR_PERIOD_TYPE_VALUE_FAILED =
  "POST_INDICATOR_PERIOD_TYPE_VALUE_FAILED";
export const POST_INDICATOR_PERIOD_TYPE_VALUE_ERROR =
  "POST_INDICATOR_PERIOD_TYPE_VALUE_ERROR";

export const POST_PRIVILEGE_VALUE = "POST_PRIVILEGE_VALUE";
export const POST_PRIVILEGE_VALUE_SUCCESS = "POST_PRIVILEGE_VALUE_SUCCESS";
export const POST_PRIVILEGE_VALUE_FAILED = "POST_PRIVILEGE_VALUE_FAILED";
export const POST_PRIVILEGE_VALUE_ERROR = "POST_PRIVILEGE_VALUE_ERROR";

export const POST_PUBLICATION_VALUE = "POST_PUBLICATION_VALUE";
export const POST_PUBLICATION_VALUE_SUCCESS = "POST_PUBLICATION_VALUE_SUCCESS";
export const POST_PUBLICATION_VALUE_FAILED = "POST_PUBLICATION_VALUE_FAILED";
export const POST_PUBLICATION_VALUE_ERROR = "POST_PUBLICATION_VALUE_ERROR";

export const POST_INDICATOR_CATEGORY_VALUE = "POST_INDICATOR_CATEGORY_VALUE";
export const POST_INDICATOR_CATEGORY_VALUE_SUCCESS =
  "POST_INDICATOR_CATEGORY_VALUE_SUCCESS";
export const POST_INDICATOR_CATEGORY_VALUE_FAILED =
  "POST_INDICATOR_CATEGORY_VALUE_FAILED";
export const POST_INDICATOR_CATEGORY_VALUE_ERROR =
  "POST_INDICATOR_CATEGORY_VALUE_ERROR";

export const POST_SOURCE_GROUP = "POST_SOURCE_GROUP";
export const POST_SOURCE_GROUP_SUCCESS = "POST_SOURCE_GROUP_SUCCESS";
export const POST_SOURCE_GROUP_FAILED = "POST_SOURCE_GROUP_FAILED";
export const POST_SOURCE_GROUP_ERROR = "POST_SOURCE_GROUP_ERROR";

export const POST_REGULAR_INDICATOR_VALUES = "POST_REGULAR_INDICATOR_VALUES";
export const POST_REGULAR_INDICATOR_VALUES_SUCCESS =
  "POST_REGULAR_INDICATOR_VALUES_SUCCESS";
export const POST_REGULAR_INDICATOR_VALUES_FAILED =
  "POST_REGULAR_INDICATOR_VALUES_FAILED";
export const POST_REGULAR_INDICATOR_VALUES_ERROR =
  "POST_REGULAR_INDICATOR_VALUES_ERROR";

export const EDIT_SECTOR = "EDIT_SECTOR";
export const EDIT_SECTOR_SUCCESS = "EDIT_SECTOR_SUCCESS";
export const EDIT_SECTOR_FAILED = "EDIT_SECTOR_FAILED";
export const EDIT_SECTOR_ERROR = "EDIT_SECTOR_ERROR";

export const DELETE_SECTOR = "DELETE_SECTOR";
export const DELETE_SECTOR_SUCCESS = "DELETE_SECTOR_SUCCESS";
export const DELETE_SECTOR_FAILED = "DELETE_SECTOR_FAILED";
export const DELETE_SECTOR_ERROR = "DELETE_SECTOR_ERROR";

export const EDIT_PERIOD_TYPE = "EDIT_PERIOD_TYPE";
export const EDIT_PERIOD_TYPE_SUCCESS = "EDIT_PERIOD_TYPE_SUCCESS";
export const EDIT_PERIOD_TYPE_FAILED = "EDIT_PERIOD_TYPE_FAILED";
export const EDIT_PERIOD_TYPE_ERROR = "EDIT_PERIOD_TYPE_ERROR";

export const DELETE_PERIOD_TYPE = "DELETE_PERIOD_TYPE";
export const DELETE_PERIOD_TYPE_SUCCESS = "DELETE_PERIOD_TYPE_SUCCESS";
export const DELETE_PERIOD_TYPE_FAILED = "DELETE_PERIOD_TYPE_FAILED";
export const DELETE_PERIOD_TYPE_ERROR = "DELETE_PERIOD_TYPE_ERROR";

export const DELETE_INDICATOR_CATEGORY = "DELETE_INDICATOR_CATEGORY";
export const DELETE_INDICATOR_CATEGORY_SUCCESS =
  "DELETE_INDICATOR_CATEGORY_SUCCESS";
export const DELETE_INDICATOR_CATEGORY_FAILED =
  "DELETE_INDICATOR_CATEGORY_FAILED";
export const DELETE_INDICATOR_CATEGORY_ERROR =
  "DELETE_INDICATOR_CATEGORY_ERROR";

export const EDIT_INDICATOR_CATEGORY = "EDIT_INDICATOR_CATEGORY";
export const EDIT_INDICATOR_CATEGORY_SUCCESS =
  "EDIT_INDICATOR_CATEGORY_SUCCESS";
export const EDIT_INDICATOR_CATEGORY_FAILED = "EDIT_INDICATOR_CATEGORY_FAILED";
export const EDIT_INDICATOR_CATEGORY_ERROR = "EDIT_INDICATOR_CATEGORY_ERROR";

export const EDIT_INDICATOR = "EDIT_INDICATOR";
export const EDIT_INDICATOR_SUCCESS = "EDIT_INDICATOR_SUCCESS";
export const EDIT_INDICATOR_FAILED = "EDIT_INDICATOR_FAILED";
export const EDIT_INDICATOR_ERROR = "EDIT_INDICATOR_ERROR";

export const DELETE_INDICATOR = "DELETE_INDICATOR";
export const DELETE_INDICATOR_SUCCESS = "DELETE_INDICATOR_SUCCESS";
export const DELETE_INDICATOR_FAILED = "DELETE_INDICATOR_FAILED";
export const DELETE_INDICATOR_ERROR = "DELETE_INDICATOR_ERROR";

export const EDIT_INDICATOR_SOURCES = "EDIT_INDICATOR_SOURCES";
export const EDIT_INDICATOR_SOURCES_SUCCESS = "EDIT_INDICATOR_SOURCES_SUCCESS";
export const EDIT_INDICATOR_SOURCES_FAILED = "EDIT_INDICATOR_SOURCES_FAILED";
export const EDIT_INDICATOR_SOURCES_ERROR = "EDIT_INDICATOR_SOURCES_ERROR";

export const DELETE_INDICATOR_SOURCE = "DELETE_INDICATOR_SOURCE";
export const DELETE_INDICATOR_SOURCE_SUCCESS =
  "DELETE_INDICATOR_SOURCE_SUCCESS";
export const DELETE_INDICATOR_SOURCE_FAILED = "DELETE_INDICATOR_SOURCE_FAILED";
export const DELETE_INDICATOR_SOURCE_ERROR = "DELETE_INDICATOR_SOURCE_ERROR";

export const EDIT_DISAGGREGATION = "EDIT_DISAGGREGATION";
export const EDIT_DISAGGREGATION_SUCCESS = "EDIT_DISAGGREGATION_SUCCESS";
export const EDIT_DISAGGREGATION_FAILED = "EDIT_DISAGGREGATION_FAILED";
export const EDIT_DISAGGREGATION_ERROR = "EDIT_DISAGGREGATION_ERROR";

export const DELETE_DISAGGREGATION = "DELETE_DISAGGREGATION";
export const DELETE_DISAGGREGATION_SUCCESS = "DELETE_DISAGGREGATION_SUCCESS";
export const DELETE_DISAGGREGATION_FAILED = "DELETE_DISAGGREGATION_FAILED";
export const DELETE_DISAGGREGATION_ERROR = "DELETE_DISAGGREGATION_ERROR";

export const EDIT_DISAGGREGATION_VALUE = "EDIT_DISAGGREGATION_VALUE";
export const EDIT_DISAGGREGATION_VALUE_SUCCESS =
  "EDIT_DISAGGREGATION_VALUE_SUCCESS";
export const EDIT_DISAGGREGATION_VALUE_FAILED =
  "EDIT_DISAGGREGATION_VALUE_FAILED";
export const EDIT_DISAGGREGATION_VALUE_ERROR =
  "EDIT_DISAGGREGATION_VALUE_ERROR";

export const DELETE_DISAGGREGATION_VALUE = "DELETE_DISAGGREGATION_VALUE";
export const DELETE_DISAGGREGATION_VALUE_SUCCESS =
  "DELETE_DISAGGREGATION_VALUE_SUCCESS";
export const DELETE_DISAGGREGATION_VALUE_FAILED =
  "DELETE_DISAGGREGATION_VALUE_FAILED";
export const DELETE_DISAGGREGATION_VALUE_ERROR =
  "DELETE_DISAGGREGATION_VALUE_ERROR";

export const DELETE_SOURCE_GROUPS = "DELETE_SOURCE_GROUPS";
export const DELETE_SOURCE_GROUPS_SUCCESS = "DELETE_SOURCE_GROUPS_SUCCESS";
export const DELETE_SOURCE_GROUPS_FAILED = "DELETE_SOURCE_GROUPS_FAILED";
export const DELETE_SOURCE_GROUPS_ERROR = "DELETE_SOURCE_GROUPS_ERROR";

export const EDIT_SOURCE_GROUPS = "EDIT_SOURCE_GROUPS";
export const EDIT_SOURCE_GROUPS_SUCCESS = "EDIT_SOURCE_GROUPS_SUCCESS";
export const EDIT_SOURCE_GROUPS_FAILED = "EDIT_SOURCE_GROUPS_FAILED";
export const EDIT_SOURCE_GROUPS_ERROR = "EDIT_SOURCE_GROUPS_ERROR";

export const DELETE_CURRENT_RELEASE = "DELETE_CURRENT_RELEASE";
export const DELETE_CURRENT_RELEASE_SUCCESS = "DELETE_CURRENT_RELEASE_SUCCESS";
export const DELETE_CURRENT_RELEASE_FAILED = "DELETE_CURRENT_RELEASE_FAILED";
export const DELETE_CURRENT_RELEASE_ERROR = "DELETE_CURRENT_RELEASE_ERROR";

export const EDIT_CURRENT_RELEASE = "EDIT_CURRENT_RELEASE";
export const EDIT_CURRENT_RELEASE_SUCCESS = "EDIT_CURRENT_RELEASE_SUCCESS";
export const EDIT_CURRENT_RELEASE_FAILED = "EDIT_CURRENT_RELEASE_FAILED";
export const EDIT_CURRENT_RELEASE_ERROR = "EDIT_CURRENT_RELEASE_ERROR";

export const DELETE_NEWS = "DELETE_NEWS";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILED = "DELETE_NEWS_FAILED";
export const DELETE_NEWS_ERROR = "DELETE_NEWS_ERROR";

export const EDIT_NEWS = "EDIT_NEWS";
export const EDIT_NEWS_SUCCESS = "EDIT_NEWS_SUCCESS";
export const EDIT_NEWS_FAILED = "EDIT_NEWS_FAILED";
export const EDIT_NEWS_ERROR = "EDIT_NEWS_ERROR";

export const EDIT_PUBLICATION = "EDIT_PUBLICATION";
export const EDIT_PUBLICATION_SUCCESS = "EDIT_PUBLICATION_SUCCESS";
export const EDIT_PUBLICATION_FAILED = "EDIT_PUBLICATION_FAILED";
export const EDIT_PUBLICATION_ERROR = "EDIT_PUBLICATION_ERROR";

export const DELETE_PUBLICATION = "DELETE_PUBLICATION";
export const DELETE_PUBLICATION_SUCCESS = "DELETE_PUBLICATION_SUCCESS";
export const DELETE_PUBLICATION_FAILED = "DELETE_PUBLICATION_FAILED";
export const DELETE_PUBLICATION_ERROR = "DELETE_PUBLICATION_ERROR";

export const REQUEST = "REQUEST";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const RESPONSE_ERROR = "REQUEST_ERROR";
export const REQUEST_ERROR = "REQUESST_ERROR";

/** 
export const POST_INDICATOR_VALUEx = "POST_INDICATOR_VALUEx";
export const POST_INDICATOR_VALUEx_SUCCESS = "POST_INDICATOR_VALUEx_SUCCESS";
export const POST_INDICATOR_VALUEx_FAILED = "POST_INDICATOR_VALUEx_FAILED";
export const POST_INDICATOR_VALUEx_ERROR = "POST_INDICATOR_VALUEx_ERROR";
**/
